ecomm/account/urls.py
from django.urls import path
from .views import (SignUpView, 
                    SignInView, 
                    SignOutView, 
                    ProfileView,
                    ProfileUpdateView, 
                    StaffListView)


app_name = "account"

urlpatterns = [
    path('signup/', SignUpView.as_view(), name="signup"),
    path('signin/', SignInView.as_view(), name="signin"),
    path('signout/', SignOutView.as_view(), name="signout"),
    path('staff/', StaffListView.as_view(), name="staff"),
    path('profile/<slug:slug>/', ProfileView.as_view(), name="profile"),
    path('profile/<slug:slug>/update/', ProfileUpdateView.as_view(), name="profile-update"),
]

ecomm/ecomm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('ecommpage.urls')),
    
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecomm/ecommpage/urls.py
from django.urls import path
from .views import (IndexListView,
                    ItemListView, 
                    ItemDetailView,
                    OrderSummaryView,
                    ItemCreateView, 
                    ItemUpdateView,
                    ItemDeleteView,
                    HistoryListView,
                    HistoryDetailView,
                    OrderStatus,
                    add_to_cart, 
                    remove_from_cart,
                    checkOut,
                    paymentComplete,
                    add_single_item_to_cart,
                    remove_single_item_from_cart,
                    )


urlpatterns = [
    path('', IndexListView.as_view(), name="index"),
    path('store', ItemListView.as_view(), name="store"),
    path('create/', ItemCreateView.as_view(), name="create"),
    path('update/<slug>/', ItemUpdateView.as_view(), name='update'),
    path('delete/<slug>/', ItemDeleteView.as_view(), name='delete'),
    path('history/', HistoryListView.as_view(), name='history'),
    path('history/<pk>/', HistoryDetailView.as_view(), name='history-detail'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('order-status/', OrderStatus.as_view(), name='order-status'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove_from_cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('add_single_item_to_cart/<slug>/', add_single_item_to_cart, name='add_single_item_to_cart'),
    path('remove_single_item_from_cart/<slug>/', remove_single_item_from_cart, name='remove_single_item_from_cart'),
    path('complete/', paymentComplete, name="complete"),
    path('check-out/', checkOut, name="check-out"),

]

ecomm/ecommpage/forms.py
from django import forms
from .models import Item
class ItemCreateForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'title',
            'description',
            'price',
            'item_quantity',
            'img',
            'category',
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'description': forms.Textarea(attrs={'class':'form-control'}),
            'price': forms.TextInput(attrs={'class':'form-control'}),
            'item_quantity': forms.TextInput(attrs={'class':'form-control'}),
        }
        
class ItemUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Item
        fields = [
            'title',
            'description',
            'price',
            'item_quantity',
            'img',
            'category',
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'description': forms.Textarea(attrs={'class':'form-control'}),
            'price': forms.TextInput(attrs={'class':'form-control'}),
            'item_quantity': forms.TextInput(attrs={'class':'form-control'}),

        }
        
        

ecomm/ecommpage/views.py
from django.shortcuts import redirect, render ,get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import (ListView, 
                                  DetailView, 
                                  CreateView, 
                                  UpdateView, 
                                  DeleteView)
from .models import (Item, 
                     Order, 
                     OrderItem)
from .forms import (ItemCreateForm, 
                    ItemUpdateForm)
from django.contrib.auth.models import User
from django_filters.views import FilterView
from account.models import Profile
from .filters import ItemFilter
from django.http import JsonResponse
import json

class ItemListView(FilterView):
    model = Item
    template_name = 'ecommpage/store.html'
    filterset_class = ItemFilter
    paginate_by = 6
    

class IndexListView(ListView):
    model = Item
    template_name = 'ecommpage/index.html'
    paginate_by = 3


class ItemDetailView(DetailView):
    model = Item
    template_name = "ecommpage/product.html"
    

class ItemCreateView(LoginRequiredMixin, CreateView):
    form_class = ItemCreateForm
    template_name = "ecommpage/create.html"
    success_url = '/'
    
    
class ItemUpdateView(LoginRequiredMixin, UpdateView):
    model = Item
    form_class = ItemUpdateForm
    template_name = "ecommpage/create.html"
    success_url = '/'
    

class ItemDeleteView(LoginRequiredMixin, DeleteView):
    
    model = Item
    template_name = "ecommpage/delete.html"
    success_url = "/"
    
    def get_object(self):
        slug = self.kwargs.get("slug")
        return get_object_or_404(Item, slug=slug)
      
class OrderSummaryView(LoginRequiredMixin, DetailView):

    def get(self, request, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'ecommpage/order_summary.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an active order")
            return redirect('store')
        
class HistoryListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = "ecommpage/history.html"
    success_url = "/"
    
    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, ordered=True).order_by('-ordered_date')
    
    
class HistoryDetailView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = "ecommpage/history_detail.html"
    success_url = "/"
    
    def get_context_data(self, *args, **kwargs):
        context = super(HistoryDetailView, self).get_context_data(**kwargs)
        context['order'] = Order.objects.filter(user=self.request.user, ordered=True)
        return context


class OrderStatus(LoginRequiredMixin, ListView):
    model = Order
    template_name = "ecommpage/orders.html"
    success_url = "/"
    
    
@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False,
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            if item.item_quantity <= order_item.quantity:
                messages.warning(request, "Out of Stock")
                return redirect("product", slug=slug)
            else:
                order_item.quantity += 1
                order_item.save()
                order.save()
                messages.success(request, "This item was updated to your cart.")
        else:
            messages.success(request, "This item was added to your cart.")
            order.items.add(order_item)
            order.save()
    else:
        order = Order.objects.create(
            user=request.user)
        order.items.add(order_item)
        order.save()
        messages.success(request, "This item was added to your cart.")
    return redirect("product", slug=slug)


@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order = Order.objects.get(user=request.user, ordered=False)
                order.delete()
                order_item.delete()
            messages.info(request, "This item quantity was updated.")
            return redirect("product", slug=slug)
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("product", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("product", slug=slug)


@login_required
def add_single_item_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False,
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            if item.item_quantity <= order_item.quantity:
                messages.warning(request, "Out of Stock")
                return redirect("product", slug=slug)
            else:
                order_item.quantity += 1
                order_item.save()
                order.save()
                messages.success(request, "This item was updated to your cart.")
        else:
            messages.success(request, "This item was added to your cart.")
            order.items.add(order_item)
            order.save()
    else:
        order = Order.objects.create(
            user=request.user)
        order.items.add(order_item)
        order.save()
        messages.success(request, "This item was added to your cart.")
    return redirect("order-summary")
 
    
@login_required
def remove_single_item_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order = Order.objects.get(user=request.user, ordered=False)
                order.delete()
                order_item.delete()
            messages.info(request, "This item quantity was updated.")
            return redirect("order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("order-summary")
    else:
        messages.info(request, "You do not have an active order")
        return redirect("order-summary")


@login_required
def checkOut(request):
    try:
        shipping_address = Profile.objects.get(user=request.user)
    except ObjectDoesNotExist:
        messages.warning(request, 'Please update first your billing address')
        return redirect('order-summary')
    try:
        order = Order.objects.get(user=request.user, ordered=False)
        for order_item in order.items.all():
            if order_item.item.item_quantity >= order_item.quantity:
                return render(request, 'ecommpage/checkout.html', {'object':order, 'shipping_address': shipping_address})
            else:
                messages.warning(request, 'Out of stock!')
                return redirect('order-summary')
    except ObjectDoesNotExist:
        messages.error(request, "You do not have an active order")
        return redirect('store')
    
@login_required
def paymentComplete(request):
    try:
        body = json.loads(request.body)
        order = Order.objects.get(id=body['orderID'])
        address = Profile.objects.get(user=request.user)
        for order_item in order.items.all():
            order_item.item.item_quantity -= order_item.quantity
            order_item.item.save()
            order_item.ordered = True
            order_item.save()
        order.shipping_address = address.get_full_address
        order.save()
        order.ordered = True
        order.total_price = body['total']
        order.save()
        messages.success(request, "Order has been processed!")
        return JsonResponse('Payment Complete', safe=False)
    except:
        messages.warning(request, "Payment did not go throuh")
        return redirect('order-summary')

    
    

ecomm/ecommpage/templates/ecommpage/checkout.html
{% extends 'account/base.html' %}

{% block content %}
<div class="container">
  
  <div class="row">
    <div class="col-lg-8 col-md-10 col-sm-12 mt-5">
      <div class="mb-2"><h1><i class="fas fa-book-open"></i> Libro</h1></div>
        <div class="container text-center">
          
        <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Item</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
                <th scope="col">Total Price</th>
              </tr>
            </thead>
            <tbody>
                {% for order_item in object.items.all %}
              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{order_item.item.title}}</td>
                <td>{{order_item.quantity}}</td>
                <td>₱ {{order_item.item.price}}</td>
                <td>₱ {{order_item.get_total_item_price}}</td>
              </tr>
              {% endfor %}
              <tr>
                <td colspan="4"><strong>Order Total</strong></td>
                <td><strong>₱ {{object.get_total}}</strong></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="clearfix col-lg-4 col-md-10 col-sm-12 p-3 mt-3 border border-secondary">
          <div class="container">
            <h3>Shipping & Billing</h3>
            <hr>
            <div class="my-4">
            <h6><strong>Name:</strong> {{shipping_address.user.first_name}} {{shipping_address.user.last_name}}</h6>
            <h6><strong>Phone Number:</strong> {{shipping_address.get_phone_number}}</h6>
            <h6><strong>Shipping address:</strong> {{shipping_address.get_full_address}}</h6>
            <small><a href="{% url 'account:profile-update' slug=user.profile.slug %}">Update</a></small>
            </div>
            <hr>
          </div>
        <div id="paypal-button-container"></div>
          <!-- Include the PayPal JavaScript SDK -->
          <script src="https://www.paypal.com/sdk/js?client-id=AXbPL2lRLTobw-HLnY0VfsSaHhpLeNwa0cH0e-EqEsVmlZFHdlaD7Gqqznn-pQDFDPBtI6xWmMGkmjct&currency=PHP"></script>
          <script>
            function getCookie(name) {
              let cookieValue = null;
              if (document.cookie && document.cookie !== '') {
                  const cookies = document.cookie.split(';');
                  for (let i = 0; i < cookies.length; i++) {
                      const cookie = cookies[i].trim();
                      // Does this cookie string begin with the name we want?
                      if (cookie.substring(0, name.length + 1) === (name + '=')) {
                          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                          break;
                      }
                  }
              }
              return cookieValue;
          }
          const csrftoken = getCookie('csrftoken');
  
            var total = '{{object.get_total}}'
            var orderID = '{{object.id}}'
  
            function completeOrder(){
              var url = "{% url 'complete' %}"
  
              fetch(url, {
                method: 'POST',
                headers:{
                  'Content-type' : "application/json",
                  'X-CSRFToken': csrftoken,
                },
                body: JSON.stringify({'orderID':orderID, 'total':total})
              })
            }
  
              // Render the PayPal button into #paypal-button-container
              paypal.Buttons({
  
                style: {
                  color:  'blue',
                  shape:  'pill',
                  label:  'pay',
                  height: 40
              },
                  // Set up the transaction
                  createOrder: function(data, actions) {
                      return actions.order.create({
                          purchase_units: [{
                              amount: {
                                  value: total
                              }
                          }]
                      });
                  },
  
                  // Finalize the transaction
                  onApprove: function(data, actions) {
                      return actions.order.capture().then(function(details) {
                          // Show a success message to the buyer
                          completeOrder()
                          alert('Transaction completed by ' + details.payer.name.given_name + '!');
                          window.location.reload();
                      });
                  }
              }).render('#paypal-button-container');
          </script>
        </div>
    </div>
</div>

{{profile.user.username}}
{% endblock %}

ecomm/ecommpage/templates/ecommpage/create.html
{% extends 'account/base.html' %}
{% block content%}
<div class="container">
    <div class="form-control w-50 mx-auto shadow">
        <form method="POST" enctype="multipart/form-data">
            <h1 class='my-3 text-center'>Post an Item</h1>
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit" class="btn btn-success my-3">Submit</button>
        </form>
    </div>

</div>
{% endblock %}

ecomm/ecommpage/templates/ecommpage/delete.html
{% extends 'account/base.html' %}
{% block content %}

<div class="container">
    <div class="card w-75">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <h5 class="card-title">Delete Post!</h5>
                <p class="card-text">Would you like to delete this object.</p>
                <button class="btn btn-danger" type="submit">Delete</button>
                <a href="{% url 'store'%}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ecomm/ecommpage/templates/ecommpage/detail.html
{% block content %}
{{object.title}}
{{object.description}}
{{object.item_quantity}}
{{object.category}}
{{object.price}}
<a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
    Add to cart
    <i class="fas fa-shopping-cart ml-1"></i>
  </a>
  <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
    Remove from cart
  </a>
{% endblock %}

ecomm/ecommpage/templates/ecommpage/history.html
{% extends 'account/base.html' %}
{% load static %}
{% block content%}
<div class="container">
    <table class="table table-striped">
       <thead>
         <tr>
           <th scope="col">#</th>
           <th scope="col">Reference Number</th>
           <th scope="col">Name</th>
           <th scope="col">Date</th>
         </tr>
       </thead>
       <tbody>
        {% for item in object_list%}
         <tr>
           <th scope="row">{{forloop.counter}}</th>
           <td><a href="{{item.get_absolute_url}}">{{item.reference_number}}</a></td>
           <td>{{item.user.first_name}} {{item.user.last_name}}</td>
           <td>{{item.ordered_date}}</td>
         </tr>
         {% endfor %}
       </tbody>
     </table>
</div>
{% endblock %}

ecomm/ecommpage/templates/ecommpage/history_detail.html
{% extends 'account/base.html' %}
{% load static %}
{% block content%}
<div class="container">
  <div class="mb-5"><h1><i class="fas fa-book-open"></i> Libro</h1></div>
  <div class="my-5">
    <h5><strong>Name:</strong> {{object.user.first_name}} {{object.user.last_name}}</h5>
    <h5><strong>Date:</strong>{{object.ordered_date}}</h5>
    <h5><strong>Phone Number:</strong> {{request.user.profile.phone_number}}</h5>
    <h5><strong>Address:</strong>{{object.shipping_address}}</h5>
  </div>

<table class="table table-striped text-center">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Reference Number</th>
        <th scope="col">Item</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>

      </tr>
    </thead>
    <tbody>
        {% for order_item in object.items.all %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{object.reference_number}}</td>
        <td>{{order_item.item.title}}</td>
        <td>{{order_item.quantity}}</td>
        <td>₱ {{order_item.item.price}}</td>
      </tr>
      {% endfor %}
      <tr>
        <td colspan="4"><strong>Order Total</strong></td>
        <td><strong>₱ {{object.total_price}}</strong></td>
      </tr>
      <tr>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}
</div>

ecomm/ecommpage/templates/ecommpage/index.html
{% extends 'account/base.html' %}
{% load static %}
{% block content%}
{% csrf_token %}
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="container carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
      <img src="{% static 'images/library1.jpg' %}" class="d-block w-100 mx-auto" style="height:550px" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>– Charles W. Eliot</h5>
        <p class="h5">“Books are the quietest and most constant of friends; they are the most accessible and wisest of counselors, and the most patient of teachers.”</p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="10000">
      <img src="{% static 'images/library2.jpg' %}" class="d-block w-100 mx-auto" style="height:550px" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>– Carl Sagan</h5>
        <p class="h5">“One glance at a book and you hear the voice of another person, perhaps someone dead for 1,000 years. To read is to voyage through time.”</p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="10000">
      <img src="{% static 'images/library3.jpg' %}" class="d-block w-100 mx-auto" style="height:550px" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>– Neil Gaiman</h5>
        <p class="h5">“Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.”</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"  data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"  data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<div class="container my-3">
  <div class="row">


  <div class="container justify-content-center my-3">
  <div class="row">
    <a href="{% url 'store' %}"><h3 class="text-center">Check out more books</h3></a>
    {% for item in object_list%}
    {% if item.item_quality != 0 %}
      <div class="col-lg-4 col-md-6 offset-md-0 offset-sm-1 col-sm-10 offset-sm-1 my-lg-0 my-2">
          <div class="card my-3 shadow"> <img class="card-img-top" src="{{ item.img.url }}">
              <div class="card-body">
                  <div class="d-flex align-items-start justify-content-between text-dark">
                      <div class="d-flex flex-column">
                          <div class="h5 font-weight-bold"><a href="{{ item.get_absolute_url }}">{{item.title}}</a></div>
                          <div class="h6 font-weight-bold">{{item.category}}</a></div>
                          <div class="text-dark">₱ {{item.price|floatformat:2}}</div>
                          <hr>
                          <div class="p font-weight-bold">{{item.description|truncatechars:100}}</a></div>
                      </div>
                  </div>
              </div>
          </div>
          
      </div>
      
      {%else %}
      {% endif %}
      {% endfor %}
    </div>
  </div>
{% endblock %}

ecomm/ecommpage/templates/ecommpage/order_summary.html
{% extends 'account/base.html' %}

{% block content %}
<div class="container">
  <div class="my-4"><h1 class='mb-2'><i class="fas fa-book-open"></i> Libro</h1></div>
 <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Item</th>
        <th scope="col">Quantity</th>
        <th scope="col">Add/Remove</th>
        <th scope="col">Price</th>
        <th scope="col">Total Price</th>

      </tr>
    </thead>
    <tbody>
        {% for order_item in object.items.all %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{order_item.item.title}}</td>
        <td>{{order_item.quantity}}</td>
        <td><a href="{% url 'add_single_item_to_cart' order_item.item.slug %}"><i class="fas fa-lg fa-plus-square"></i></a> <a href="{% url 'remove_single_item_from_cart' order_item.item.slug %}"><i class="fas fa-lg fa-minus-square"></i></a></td>
        <td>₱ {{order_item.item.price}}</td>
        <td>₱ {{order_item.get_total_item_price}}</td>
      </tr>
      {% endfor %}
      <tr>
        <td colspan="5"><strong>Order Total</strong></td>
        <td><strong>₱ {{object.get_total}}</strong></td>
      </tr>
      <tr>
        <td colspan="6">
          <a class='btn btn-danger float-end' href="{% url 'check-out' %}">CashOut</a>
          <a class='btn btn-primary float-end ml-4' href="{% url 'store' %}">Continue Shopping</a>
        </td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

ecomm/ecommpage/templates/ecommpage/orders.html
{% extends 'account/base.html' %}
{% load static %}
{% block content%}
<div class="container">
  <div class="my-4"><h1 class='mb-2'><i class="fas fa-book-open"></i> Libro</h1></div>
<table class="table table-striped text-center">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Reference Number</th>
        <th scope="col">Name</th>
        <th scope="col">Date</th>
        <th scope="col">Status</th>

      </tr>
    </thead>
    <tbody>
        {% for order_item in object_list %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{order_item.reference_number}}</td>
        <td>{{order_item.user}}</td>
        <td>{{order_item.ordered_date}}</td>
        <td>{% if order_item.delivered %}
          <strong>Delivered</strong>
          {% else %}
          <strong>On Transit</strong>
        {% endif %}
      </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

ecomm/ecommpage/templates/ecommpage/update.html
{% extends 'account/base.html' %}
{% block content%}
<div class="container">
    <div class="form-control w-50 mx-auto shadow">
        <form method="POST" enctype="multipart/form-data">
            <h1 class='my-3 text-center'>Sign Up</h1>
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit" class="btn btn-success my-3">Submit</button>
        </form>
    </div>

</div>
{% endblock %}